config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'projects#index'

  resources :projects
  resources :comments
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :project
  belongs_to :user

  validates :description, presence: true
  validates :project_id, presence: true
  validates :user_id, presence: true
end

app/models/project.rb
class Project < ApplicationRecord
  has_many :comments, dependent: :destroy

  enum status: %i[backlog planning ready_to_dev in_progress review qa ready_to_deploy done]

  validates :name, presence: true
  validates :status, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  NotAuthorizedError = Class.new(StandardError)

  before_action :authenticate_user!

  skip_forgery_protection

  def create
    @comment = Comment.new(comment_params)

    if @comment.save
      render json: @comment, status: :created
    else
      render json: @comment.errors, status: :unprocessable_entity
    end
  end

  def update
    @comment = Comment.find(params[:id])

    authorize(@comment)

    if @comment.update(comment_params)
      render json: @comment, status: :ok
    else
      render json: @comment.errors, status: :unprocessable_entity
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:description, :post_id, :project_id).merge(user: current_user)
  end

  def authorize(resource)
    raise NotAuthorizedError unless resource.user_id == current_user.id
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :authenticate_user!

  skip_forgery_protection

  def index
    @projects = Project.all
  end

  def show
    @project = Project.find(params[:id])
  end

  def update
    @project = Project.find(params[:id])

    if @project.update(project_params)
      log_status_update
      render json: @project, status: :ok
    else
      render json: @project.errors, status: :unprocessable_entity
    end
  end

  private

  def project_params
    params.require(:project).permit(:status)
  end

  def log_status_update
    Comment.create(
      user: current_user,
      project: @project,
      description: "Project status updated to #{project_params[:status].humanize}"
    )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.html.slim
h1 Hello

app/views/layouts/application.html.slim
doctype html
html
  head
    title ProjectManager
    meta name='viewport' content='width=device-width,initial-scale=1'
    = csrf_meta_tags
    = csp_meta_tag

    = stylesheet_link_tag "application", "data-turbo-track": "reload"
    link rel='stylesheet' href='https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css' integrity='sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N' crossorigin='anonymous'

    = javascript_importmap_tags

  body
    .container
      .col-md-12.mt-2.h-25.d-inline-block
        - if user_signed_in?
          .float-right
            = button_to 'Log Out', destroy_user_session_path, method: :delete, class: "btn btn-danger"
      .col-md-12
        .mt-5
          = yield

app/views/projects/_comments.html.slim
div.mt-4 data-controller="comments"
  h2 Comments
  div data-target="comments.list" data-project-id="#{@project.id}"
    - @project.comments.each do |comment|
      .font-weight-bold.mt-3 = comment.user.email

      - if comment.user_id != current_user.id || comment.description.include?('Project status')
        .card.card-body.mt-2 data-comment-id="#{comment.id}"
          = comment.description
      - else
        .card.card-body.mt-2 data-action="click->comments#editComment" data-comment-id="#{comment.id}"
          = comment.description
  form.mt-4 data-action="submit->comments#upsertComment"
    input type="text" data-target="comments.form"
    input type="submit" data-target="comments.submitButton" value="Add Comment"

app/views/projects/index.html.slim
div#accordion
  - @projects.each do |project|
    = link_to project_path(project), class: 'text-decoration-none text-dark' do
      div.card.mb-2
        div.card-header
          h5.mb-0
            = project.name

app/views/projects/show.html.slim
h1 Project Details
div.card data-controller="projects" data-project-id="#{@project.id}"
  div.card-body
    h5.card-title= @project.name
    p.card-text= @project.description
    p Status:
    select data-target="projects.status" data-action="change->projects#updateStatus"
      - Project.statuses.keys.each do |status|
        - if status == @project.status
          option[value="#{status}" selected] = status.humanize
        - else
          option value="#{status}" = status.humanize

= link_to 'Back to Projects', projects_path, class: 'btn btn-primary mt-3'
= render 'comments'